apiVersion: v1
kind: Service
metadata:
  name: service-web-app
  labels:
    app: sample-web-app
spec:
  selector:
    app: sample-web-app
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30146

